### ISSUE TITLE
events not work

### ISSUE THREAD

**Issue by 313364973** [noffle/nano-ecs#2]
first , thanks  
this project helps me much.
but i have a problem when i use event ,it seems not work.
here is my code 

var nano = require('nano-ecs')
var world = nano()

function Health () {
    this.hp = 100
}

var entity = world.createEntity()
var b = world.createEntity()

entity.addComponent(Health)

entity.on('damage', function (amount) {
    this.hp -= amount
    if (this.hp < 0) {
        entity.emit('death')
    }
})
b.emit('damage')

the damage function not fired.

**Comment by hackergrrl** [comment]
Hi @313364973. It looks like you're listening for `damage` on `entity`, but firing the event on `b`.
